### ISSUE TITLE
前置要求

### ISSUE THREAD

**Issue by edwinhuish** [xlzy520/baby-life#1]
```
前置要求

开启一个云服务，选择好云服务空间，在config.js中配置
创建好云数据库(blog、album、user), 上传云函数(位于static文件夹中)
Node.js > 12
启动项目，具体使用方式看如下项目 [uniapp-tailwind-uview-starter](https://github.com/xlzy520/uniapp-tailwind-uview-starter)
```

请问开启一个云服务指的是什么云服务呢？ 微信的云服务？

上传云函数指的是哪个呢？

**Comment by xlzy520** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/28336270/160044163-97ffb08a-2fe1-438b-abd8-abfe104edbbc.png">

**Comment by xlzy520** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/28336270/160044220-ee9b959a-9316-4b0f-9f0d-ccb6593764c6.png">

**Comment by xlzy520** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/28336270/160044247-015b1e7c-6c88-4caf-b35d-a829bcc0839e.png">

**Comment by edwinhuish** [comment]
谢谢，一直不用HBuilder，单纯用vscode开发uni-app，所以不知道有这个功能。

家中领导也提到了类似的需求，准备在自家的nas上部署这个私密朋友圈。谢谢你的开源。

**Comment by xlzy520** [comment]
@edwinhuish 我记错了，不需要这样。可以直接在微信开发者工具里面有云开发，在那里进行关联，不需要Hbuilder

**Comment by xlzy520** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/28336270/160079261-60628ada-10e2-40bf-93d1-ab91131a5543.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/28336270/160079314-d3671731-bd9f-4d36-a3bf-afb19e3c86bb.png">
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/28336270/160079344-d3a718a4-9a7d-4470-9f19-9d741ea24893.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/28336270/160079395-d4b07f39-576d-4512-a35c-c9255a3f1b94.png">

**Comment by xlzy520** [comment]
过了太久了，不懂的话还需要你去查看一下微信小程序的云开发教程

**Comment by edwinhuish** [comment]
> 过了太久了，不懂的话还需要你去查看一下微信小程序的云开发教程

请问你现在还在使用这个吗？存储是使用CDN吗？还是说有更好的解决方案？

**Comment by xlzy520** [comment]
就是微信小程序自带的云开发，它提供免费的数据库和存储空间


 
---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2022年3月25日 16:05:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xlzy520/baby-life] 前置要求 (Issue #1)




  
过了太久了，不懂的话还需要你去查看一下微信小程序的云开发教程
  
请问你现在还在使用这个吗？存储是使用CDN吗？还是说有更好的解决方案？
